# Generated by Django 5.0.7 on 2024-07-16 22:28

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continuity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Must be unique.', max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='nominator',
            name='nominator_lower_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='nominatorright',
            name='nominator_right_lower_name_unique',
        ),
        migrations.AlterField(
            model_name='nomination',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='Must be after Started At', null=True),
        ),
        migrations.AddConstraint(
            model_name='nominator',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='nominator_lower_name_unique', violation_error_message='Nominator already exists (case insensitive)'),
        ),
        migrations.AddConstraint(
            model_name='nominatorright',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='nominator_right_lower_name_unique', violation_error_message='Nominator Right already exists (case insensitive)'),
        ),
        migrations.AddConstraint(
            model_name='continuity',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='continuity_lower_name_unique', violation_error_message='Continuity already exists (case insensitive)'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='continuities',
            field=models.ManyToManyField(to='nominations.continuity'),
        ),
    ]
