# Generated by Django 5.0.7 on 2024-07-17 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0002_continuity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominatorrighttimeframe',
            name='right',
            field=models.IntegerField(choices=[(1, 'Agri Corp'), (2, 'Edu Corp'), (3, 'Inquisitor'), (4, 'Banned')]),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 17, 23, 46, 34, 866861, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.IntegerField(choices=[(1, 'Category'), (2, 'Intellectual Property')], default=1, help_text='If Intellectual Property is chosen, the name will render in italics.'),
        ),
        migrations.DeleteModel(
            name='NominatorRight',
        ),
    ]
