# Generated by Django 5.0.7 on 2024-07-16 12:45

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(help_text='Must be unique.', max_length=200, unique=True)),
                ('category', models.IntegerField(choices=[(1, 'Featured'), (2, 'Good'), (3, 'Comprehensive')])),
                ('outcome', models.IntegerField(choices=[(1, 'Successful'), (2, 'Unsuccessful'), (3, 'Withdrawn'), (4, 'Other')])),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(help_text='Must be after Started At', null=True)),
                ('start_word_count', models.IntegerField(blank=True, null=True)),
                ('end_word_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nominator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Must be unique.', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NominatorRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Must be unique.', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NominatorRightTimeframe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Must be unique.', max_length=200, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='nominator',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='nominator_lower_name_unique', violation_error_message='WookieProject name already exists (case insensitive)'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='nominators',
            field=models.ManyToManyField(to='nominations.nominator'),
        ),
        migrations.AddConstraint(
            model_name='nominatorright',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='nominator_right_lower_name_unique', violation_error_message='Right already exists (case insensitive)'),
        ),
        migrations.AddField(
            model_name='nominatorrighttimeframe',
            name='nominator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nominations.nominator'),
        ),
        migrations.AddField(
            model_name='nominatorrighttimeframe',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nominations.nominatorright'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='project_lower_name_unique', violation_error_message='WookieProject name already exists (case insensitive)'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='projects',
            field=models.ManyToManyField(to='nominations.project'),
        ),
        migrations.AddConstraint(
            model_name='nomination',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('article_name'), name='nomination_lower_article_name_unique', violation_error_message='Article Name already exists (case insensitive)'),
        ),
    ]
